services:
  postgres:
    image: postgres:16-alpine
    container_name: saas-starter-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas-starter
    ports:
      - "5436:5432"
    volumes:
      - saas_starter_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  saas_starter_postgres_data: